import type { OriginWorkflow } from "./workflow.js";

export const INCIDENT_RESPONSE_WORKFLOW: OriginWorkflow = {
  id: "incident-response",
  title: "Incident Response Burst",
  summary:
    "A room-level incident where agents share repeated provenance and context, making frame compression valuable.",
  steps: [
    {
      id: "observe-room",
      label: "Camera agent establishes the room state",
      packet: {
        version: "O1",
        id: "hx21-p1",
        agent: "self",
        kind: "assert",
        claims: [
          { subject: "door", relation: "=", object: "open" },
          { subject: "alarm", relation: "=", object: "off" },
        ],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.91,
        intent: "observe",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "heat-check",
      label: "Camera agent reports thermal anomaly",
      packet: {
        version: "O1",
        id: "hx21-p2",
        agent: "self",
        kind: "assert",
        claims: [{ subject: "heat", relation: ">", object: "42" }],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.88,
        intent: "verify",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "vent-proposal",
      label: "Camera agent proposes a local actuator response",
      packet: {
        version: "O1",
        id: "hx21-p3",
        agent: "self",
        kind: "propose",
        claims: [{ subject: "vent", relation: "=", object: "on" }],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.84,
        intent: "act",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "distress-assert",
      label: "Support agent confirms distress from audio and text",
      packet: {
        version: "O1",
        id: "hx21-p4",
        agent: "peer7",
        kind: "assert",
        claims: [{ subject: "user", relation: "=", object: "distress" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.83,
        intent: "notify",
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "medic-commit",
      label: "Support agent commits a responder route",
      packet: {
        version: "O1",
        id: "hx21-p5",
        agent: "peer7",
        kind: "commit",
        claims: [{ subject: "medic", relation: "->", object: "roomA" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.86,
        intent: "assist",
        respondsTo: "hx21-p4",
        dependsOn: ["hx21-p3"],
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "corridor-check",
      label: "Support agent reports an uncertain corridor state",
      packet: {
        version: "O1",
        id: "hx21-p6",
        agent: "peer7",
        kind: "assert",
        claims: [{ subject: "corridor", relation: "=", object: "blocked" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.61,
        intent: "verify",
        respondsTo: "hx21-p5",
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "route-revise",
      label: "Support agent revises the responder route after blockage",
      packet: {
        version: "O1",
        id: "hx21-p7",
        agent: "peer7",
        kind: "revise",
        claims: [{ subject: "medic", relation: "->", object: "serviceEntry" }],
        evidence: [
          { kind: "text", ref: "88" },
          { kind: "voice", ref: "44" },
        ],
        confidence: 0.78,
        intent: "assist",
        respondsTo: "hx21-p5",
        dependsOn: ["hx21-p6"],
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
  ],
};
