import type { OriginWorkflow } from "./workflow.js";

export const INCIDENT_RESPONSE_WORKFLOW: OriginWorkflow = {
  id: "incident-response",
  title: "Incident Response Burst",
  summary:
    "A room-level incident where agents share repeated provenance and context, making frame compression valuable.",
  steps: [
    {
      id: "observe-room",
      label: "Camera agent establishes the room state",
      packet: {
        version: "O1",
        id: "hx21-p1",
        agent: "self",
        kind: "assert",
        claims: [
          { subject: "door", relation: "=", object: "open" },
          { subject: "alarm", relation: "=", object: "off" },
        ],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.91,
        intent: "observe",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "heat-check",
      label: "Camera agent reports thermal anomaly",
      packet: {
        version: "O1",
        id: "hx21-p2",
        agent: "self",
        kind: "assert",
        claims: [{ subject: "heat", relation: ">", object: "42" }],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.88,
        intent: "verify",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "vent-proposal",
      label: "Camera agent proposes a local actuator response",
      packet: {
        version: "O1",
        id: "hx21-p3",
        agent: "self",
        kind: "propose",
        claims: [{ subject: "vent", relation: "=", object: "on" }],
        evidence: [{ kind: "cam", ref: "12@14:03" }],
        confidence: 0.84,
        intent: "act",
        context: { incident: "HX21", room: "A" },
      },
    },
    {
      id: "distress-assert",
      label: "Support agent confirms distress from audio and text",
      packet: {
        version: "O1",
        id: "hx21-p4",
        agent: "peer7",
        kind: "assert",
        claims: [{ subject: "user", relation: "=", object: "distress" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.83,
        intent: "notify",
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "medic-commit",
      label: "Support agent commits a responder route",
      packet: {
        version: "O1",
        id: "hx21-p5",
        agent: "peer7",
        kind: "commit",
        claims: [{ subject: "medic", relation: "->", object: "roomA" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.86,
        intent: "assist",
        respondsTo: "hx21-p4",
        dependsOn: ["hx21-p3"],
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "corridor-check",
      label: "Support agent reports an uncertain corridor state",
      packet: {
        version: "O1",
        id: "hx21-p6",
        agent: "peer7",
        kind: "assert",
        claims: [{ subject: "corridor", relation: "=", object: "blocked" }],
        evidence: [
          { kind: "voice", ref: "44" },
          { kind: "text", ref: "88" },
        ],
        confidence: 0.61,
        intent: "verify",
        respondsTo: "hx21-p5",
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
    {
      id: "route-revise",
      label: "Support agent revises the responder route after blockage",
      packet: {
        version: "O1",
        id: "hx21-p7",
        agent: "peer7",
        kind: "revise",
        claims: [{ subject: "medic", relation: "->", object: "serviceEntry" }],
        evidence: [
          { kind: "text", ref: "88" },
          { kind: "voice", ref: "44" },
        ],
        confidence: 0.78,
        intent: "assist",
        respondsTo: "hx21-p5",
        dependsOn: ["hx21-p6"],
        context: { incident: "HX21", priority: "high", room: "A" },
      },
    },
  ],
};

export const FACILITY_EGRESS_WORKFLOW: OriginWorkflow = {
  id: "facility-egress",
  title: "Facility Egress Relay",
  summary:
    "A repeated multi-zone evacuation pattern where the same routing grammar appears across several frames, making adaptive FW1 lexicons worthwhile.",
  steps: [
    {
      id: "zone-a-state",
      label: "Camera sweep establishes zone A state",
      packet: {
        version: "O1",
        id: "eg7-a1",
        agent: "self",
        kind: "assert",
        claims: [
          { subject: "door", relation: "=", object: "open" },
          { subject: "exit", relation: "=", object: "ready" },
        ],
        evidence: [{ kind: "cam", ref: "21@08:00" }],
        confidence: 0.93,
        intent: "observe",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "A",
        },
      },
    },
    {
      id: "zone-a-crowd",
      label: "Camera sweep estimates zone A crowd size",
      packet: {
        version: "O1",
        id: "eg7-a2",
        agent: "self",
        kind: "assert",
        claims: [{ subject: "crowd", relation: "=", object: "42" }],
        evidence: [{ kind: "cam", ref: "21@08:00" }],
        confidence: 0.89,
        intent: "verify",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "A",
        },
      },
    },
    {
      id: "zone-a-egress",
      label: "Camera sweep proposes zone A egress route",
      packet: {
        version: "O1",
        id: "eg7-a3",
        agent: "self",
        kind: "propose",
        claims: [{ subject: "evac", relation: "->", object: "stagingA" }],
        evidence: [{ kind: "cam", ref: "21@08:00" }],
        confidence: 0.86,
        intent: "act",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "A",
        },
      },
    },
    {
      id: "zone-b-state",
      label: "Camera sweep establishes zone B state",
      packet: {
        version: "O1",
        id: "eg7-b1",
        agent: "self",
        kind: "assert",
        claims: [
          { subject: "door", relation: "=", object: "open" },
          { subject: "exit", relation: "=", object: "ready" },
        ],
        evidence: [{ kind: "cam", ref: "22@08:02" }],
        confidence: 0.92,
        intent: "observe",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "B",
        },
      },
    },
    {
      id: "zone-b-crowd",
      label: "Camera sweep estimates zone B crowd size",
      packet: {
        version: "O1",
        id: "eg7-b2",
        agent: "self",
        kind: "assert",
        claims: [{ subject: "crowd", relation: "=", object: "39" }],
        evidence: [{ kind: "cam", ref: "22@08:02" }],
        confidence: 0.88,
        intent: "verify",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "B",
        },
      },
    },
    {
      id: "zone-b-egress",
      label: "Camera sweep proposes zone B egress route",
      packet: {
        version: "O1",
        id: "eg7-b3",
        agent: "self",
        kind: "propose",
        claims: [{ subject: "evac", relation: "->", object: "stagingB" }],
        evidence: [{ kind: "cam", ref: "22@08:02" }],
        confidence: 0.85,
        intent: "act",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "B",
        },
      },
    },
    {
      id: "zone-c-state",
      label: "Camera sweep establishes zone C state",
      packet: {
        version: "O1",
        id: "eg7-c1",
        agent: "self",
        kind: "assert",
        claims: [
          { subject: "door", relation: "=", object: "open" },
          { subject: "exit", relation: "=", object: "ready" },
        ],
        evidence: [{ kind: "cam", ref: "23@08:04" }],
        confidence: 0.92,
        intent: "observe",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "C",
        },
      },
    },
    {
      id: "zone-c-crowd",
      label: "Camera sweep estimates zone C crowd size",
      packet: {
        version: "O1",
        id: "eg7-c2",
        agent: "self",
        kind: "assert",
        claims: [{ subject: "crowd", relation: "=", object: "41" }],
        evidence: [{ kind: "cam", ref: "23@08:04" }],
        confidence: 0.9,
        intent: "verify",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "C",
        },
      },
    },
    {
      id: "zone-c-egress",
      label: "Camera sweep proposes zone C egress route",
      packet: {
        version: "O1",
        id: "eg7-c3",
        agent: "self",
        kind: "propose",
        claims: [{ subject: "evac", relation: "->", object: "stagingC" }],
        evidence: [{ kind: "cam", ref: "23@08:04" }],
        confidence: 0.87,
        intent: "act",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "sweep",
          priority: "high",
          zone: "C",
        },
      },
    },
    {
      id: "zone-a-escort",
      label: "Dispatch commits escort route for zone A",
      packet: {
        version: "O1",
        id: "eg7-d1",
        agent: "peer7",
        kind: "commit",
        claims: [{ subject: "escort", relation: "->", object: "stagingA" }],
        evidence: [{ kind: "radio", ref: "ops72" }],
        confidence: 0.9,
        intent: "assist",
        respondsTo: "eg7-a3",
        dependsOn: ["eg7-a1"],
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "dispatch",
          priority: "high",
          zone: "A",
        },
      },
    },
    {
      id: "zone-b-escort",
      label: "Dispatch commits escort route for zone B",
      packet: {
        version: "O1",
        id: "eg7-d2",
        agent: "peer7",
        kind: "commit",
        claims: [{ subject: "escort", relation: "->", object: "stagingB" }],
        evidence: [{ kind: "radio", ref: "ops72" }],
        confidence: 0.89,
        intent: "assist",
        respondsTo: "eg7-b3",
        dependsOn: ["eg7-b1"],
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "dispatch",
          priority: "high",
          zone: "B",
        },
      },
    },
    {
      id: "zone-c-escort",
      label: "Dispatch commits escort route for zone C",
      packet: {
        version: "O1",
        id: "eg7-d3",
        agent: "peer7",
        kind: "commit",
        claims: [{ subject: "escort", relation: "->", object: "stagingC" }],
        evidence: [{ kind: "radio", ref: "ops72" }],
        confidence: 0.9,
        intent: "assist",
        respondsTo: "eg7-c3",
        dependsOn: ["eg7-c1"],
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "dispatch",
          priority: "high",
          zone: "C",
        },
      },
    },
    {
      id: "zone-a-corridor",
      label: "Navigation agent verifies corridor clearance for zone A",
      packet: {
        version: "O1",
        id: "eg7-n1",
        agent: "peer9",
        kind: "assert",
        claims: [{ subject: "corridor", relation: "=", object: "clear" }],
        evidence: [
          { kind: "map", ref: "ingress3" },
          { kind: "log", ref: "nav88" },
        ],
        confidence: 0.87,
        intent: "verify",
        respondsTo: "eg7-d1",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "route",
          priority: "high",
          zone: "A",
        },
      },
    },
    {
      id: "zone-b-corridor",
      label: "Navigation agent verifies corridor clearance for zone B",
      packet: {
        version: "O1",
        id: "eg7-n2",
        agent: "peer9",
        kind: "assert",
        claims: [{ subject: "corridor", relation: "=", object: "clear" }],
        evidence: [
          { kind: "map", ref: "ingress3" },
          { kind: "log", ref: "nav88" },
        ],
        confidence: 0.88,
        intent: "verify",
        respondsTo: "eg7-d2",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "route",
          priority: "high",
          zone: "B",
        },
      },
    },
    {
      id: "zone-c-corridor",
      label: "Navigation agent verifies corridor clearance for zone C",
      packet: {
        version: "O1",
        id: "eg7-n3",
        agent: "peer9",
        kind: "assert",
        claims: [{ subject: "corridor", relation: "=", object: "clear" }],
        evidence: [
          { kind: "map", ref: "ingress3" },
          { kind: "log", ref: "nav88" },
        ],
        confidence: 0.88,
        intent: "verify",
        respondsTo: "eg7-d3",
        context: {
          facility: "ALPHA",
          mission: "EG7",
          phase: "route",
          priority: "high",
          zone: "C",
        },
      },
    },
  ],
};

export const WORKFLOW_CORPUS: OriginWorkflow[] = [
  INCIDENT_RESPONSE_WORKFLOW,
  FACILITY_EGRESS_WORKFLOW,
];
